### ISSUE TITLE
Sub domain with trailing . fails

### ISSUE THREAD

**Issue by xnl-h4ck3r** [mrrootsec/AssetViz#1]
Great tool! One small thing...
If there is a sub domain in the input file that ends with a dot `.` then it gives the error `File contains invalid input`.
Some tools may have output with a trailing dot (something in my tool chain must have) so maybe you could strip a trailing `.`? Or give a more specific error in that case so the user knows what the issue couid be?

**Comment by mrrootsec** [comment]
Thank you for the heads-up mate @xnl-h4ck3r !
I've fixed the issue by stripping trailing dots from subdomains in the input.
